# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(default='', upload_to='')),
                ('likes', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bir_day', models.DateField()),
                ('country', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
