# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syte', '0002_auto_20180324_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Profil',
        ),
    ]
